import { writable } from 'svelte/store';
export const mapConfig = writable({
  "title": "How much did train ticket prices change in the European Union?",
  "subtitle": "While train travel prices soared by 16% in Romania and over 6% in Germany in 2025, countries like Croatia and Lithuania saw fares drop by up to 4%.",
  "colourSchemeClasses": 7,
  "data": "country,id,value,extraInfo,text_content,link_text,link_url_target,audio_url_1,audio_url_2,audio_url_3,image_url_source,image_url_target,video_url\nBelgium,BE,0.005,FALSE,,,,,,,,,\nBulgaria,BG,0.034,FALSE,,,,,,,,,\nCzechia,CZ,0.043,FALSE,,,,,,,,,\nDenmark,DK,0.020,FALSE,,,,,,,,,\nGermany,DE,0.063,FALSE,,,,,,,,,\nEstonia,EE,0.022,FALSE,,,,,,,,,\nIreland,IE,-0.005,FALSE,,,,,,,,,\nGreece,EL,0.000,FALSE,,,,,,,,,\nSpain,ES,0.003,FALSE,,,,,,,,,\nFrance,FR,0.002,FALSE,,,,,,,,,\nCroatia,HR,-0.040,FALSE,,,,,,,,,\nItaly,IT,0.003,FALSE,,,,,,,,,\nCyprus,CY,,FALSE,,,,,,,,,\nLatvia,LV,0.049,FALSE,,,,,,,,,\nLithuania,LT,-0.035,FALSE,,,,,,,,,\nLuxembourg,LU,0.014,FALSE,,,,,,,,,\nHungary,HU,-0.008,FALSE,,,,,,,,,\nMalta,MT,,FALSE,,,,,,,,,\nNetherlands,NL,0.062,FALSE,,,,,,,,,\nAustria,AT,0.061,FALSE,,,,,,,,,\nPoland,PL,-0.008,FALSE,,,,,,,,,\nPortugal,PT,-0.002,FALSE,,,,,,,,,\nRomania,RO,0.160,FALSE,,,,,,,,,\nSlovenia,SI,0.003,FALSE,,,,,,,,,\nSlovakia,SK,0.091,FALSE,,,,,,,,,\nFinland,FI,0.057,FALSE,,,,,,,,,\nSweden,SE,0.036,FALSE,,,,,,,,,",
  "parsedData": [
    {
      "country": "Belgium",
      "id": "BE",
      "value": 0.005,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Bulgaria",
      "id": "BG",
      "value": 0.034,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Czechia",
      "id": "CZ",
      "value": 0.043,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Denmark",
      "id": "DK",
      "value": 0.02,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Germany",
      "id": "DE",
      "value": 0.063,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Estonia",
      "id": "EE",
      "value": 0.022,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Ireland",
      "id": "IE",
      "value": -0.005,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Greece",
      "id": "EL",
      "value": 0,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Spain",
      "id": "ES",
      "value": 0.003,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "France",
      "id": "FR",
      "value": 0.002,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Croatia",
      "id": "HR",
      "value": -0.04,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Italy",
      "id": "IT",
      "value": 0.003,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Cyprus",
      "id": "CY",
      "value": null,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Latvia",
      "id": "LV",
      "value": 0.049,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Lithuania",
      "id": "LT",
      "value": -0.035,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Luxembourg",
      "id": "LU",
      "value": 0.014,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Hungary",
      "id": "HU",
      "value": -0.008,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Malta",
      "id": "MT",
      "value": null,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Netherlands",
      "id": "NL",
      "value": 0.062,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Austria",
      "id": "AT",
      "value": 0.061,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Poland",
      "id": "PL",
      "value": -0.008,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Portugal",
      "id": "PT",
      "value": -0.002,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Romania",
      "id": "RO",
      "value": 0.16,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovenia",
      "id": "SI",
      "value": 0.003,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Slovakia",
      "id": "SK",
      "value": 0.091,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Finland",
      "id": "FI",
      "value": 0.057,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    },
    {
      "country": "Sweden",
      "id": "SE",
      "value": 0.036,
      "extraInfo": false,
      "text_content": "",
      "link_text": "",
      "link_url_target": "",
      "audio_url_1": "",
      "audio_url_2": "",
      "audio_url_3": "",
      "image_url_source": "",
      "image_url_target": "",
      "video_url": ""
    }
  ],
  "datasetType": "values",
  "datasetUnit": "percent",
  "percentRounded": false,
  "colourSchemeType": "sequential",
  "colourScheme": "red",
  "colourSchemeReverse": false,
  "headlineAvailable": true,
  "subheadlineAvailable": true,
  "tooltipAvailable": true,
  "scaleBarAvailable": true,
  "overrideScaleValues": false,
  "legendAvailable": true,
  "textSourceAvailable": true,
  "textSourceDescription": "Source",
  "textSource": "Eurostat (2026)",
  "textNoteAvailable": true,
  "textNoteDescription": "Note",
  "textNote": "The map is based on the Harmonised Index of Consumer Prices (HICP), which measures changes in consumer prices over time. The indicator shown is the annual average rate of change, comparing the average price index of one calendar year with the average of the previous year. The data follows the ECOICOP classification, base year 2025=100.",
  "textDataAccessAvailable": true,
  "linkDataAccessDescription": "Access the data",
  "linkDataAccess": "https://ec.europa.eu/eurostat/databrowser/view/prc_hicp_ainr__custom_21608572/default/table",
  "legend1": "No data available",
  "legend1Color": "#E0E0E0",
  "customUnitLabelAvailable": false,
  "customUnitLabel": "",
  "tooltipExtraInfoLabel": "Click here",
  "translate": {
    "title": "How much did train ticket prices change in the European Union?",
    "subtitle": "While train travel prices soared by 16% in Romania and over 6% in Germany in 2025, countries like Croatia and Lithuania saw fares drop by up to 4%.",
    "textNoteDescription": "Note",
    "textNote": "The map is based on the Harmonised Index of Consumer Prices (HICP), which measures changes in consumer prices over time. The indicator shown is the annual average rate of change, comparing the average price index of one calendar year with the average of the previous year. The data follows the ECOICOP classification, base year 2025=100.",
    "textSourceDescription": "Source",
    "textSource": "Eurostat (2026)",
    "linkDataAccessDescription": "Access the data",
    "legend1": "No data available",
    "tooltipExtraInfoLabel": "Click here"
  },
  "clusters": [],
  "colorScale": null
});